version: '3.9'
name: 'postgres_testes'

services:
  #Data Base
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=teste
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '2GB'